baseURL: https://blog.thalheim.io/
languageCode: en-us
defaultContentLanguage: en
theme:
  - hugo-atom-feed
  - hugo-vitae
paginate: 5
title: ~/git/blog
author: Mic92
disqusShortname: mic92
copyright: © 2021 Jörg Thalheim
pygmentsstyle: "dracula"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
enableRobotsTXT: true

outputs:
  # <domain>/atom.xml
  home:
    - HTML
    - RSS
    - ATOM
  # <domain>/posts/atom.xml
  section:
    - HTML
    - RSS
    - ATOM
  # <domain>/tags/mytag/atom.xml, <domain>/categories/mycat/atom.xml
  taxonomy:
    - HTML
    - RSS
    - ATOM
ignoreErrors:
  - error-output-taxonomy
permalinks:
  posts: /:year/:month/:day/:title/

menu:
  main:
    - name: Home
      url: /
      weight: 1

    - name: All Posts
      url: /posts
      weight: 2

    - name: Categories
      url: /categories
      weight: 5

params:
  listAuthor: true
  comments:
    enabled: true
  subtitle: "My brain-dump of random code/configuration."
  social:
    - name: RSS
      url: /index.xml
      icon: fas fa-rss
    - name: Github
      icon: fab fa-github
      url: https://github.com/Mic92/blog
