name: typo checker

concurrency:
  group: typo-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - staging # bors
      - trying # bors
jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v3

    - name: Ignore implicit configuration file
      uses: crate-ci/typos@master
